"""remove asset_type col from asset table

Revision ID: 3b2342156055
Revises: 981b1135209c
Create Date: 2026-02-21 17:01:04.505872

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3b2342156055"
down_revision: Union[str, Sequence[str], None] = "981b1135209c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "asset_transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_asset_transactions_id"), "asset_transactions", ["id"], unique=False
    )
    op.drop_index(op.f("idx_symbol_asset_type"), table_name="stocks")
    op.create_index(op.f("ix_stocks_symbol"), "stocks", ["symbol"], unique=False)
    op.drop_column("stocks", "asset_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks",
        sa.Column(
            "asset_type",
            sa.VARCHAR(length=20),
            server_default=sa.text("'stock'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_stocks_symbol"), table_name="stocks")
    op.create_index(
        op.f("idx_symbol_asset_type"), "stocks", ["symbol", "asset_type"], unique=False
    )
    op.drop_index(op.f("ix_asset_transactions_id"), table_name="asset_transactions")
    op.alter_column(
        "asset_transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
