"""update stock table

Revision ID: 6a3ba15164f3
Revises: cf066abd5a88
Create Date: 2025-12-24 15:49:31.932534

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a3ba15164f3"
down_revision: Union[str, Sequence[str], None] = "cf066abd5a88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column("stocks", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column("stocks", sa.Column("cost", sa.Float(), nullable=True))

    op.execute("UPDATE stocks SET name = 'NULL' WHERE name IS NULL")
    op.execute("UPDATE stocks SET cost = prum * shares_number WHERE cost IS NULL")

    # Now make the columns non-nullable
    op.alter_column("stocks", "name", nullable=False)
    op.alter_column("stocks", "cost", nullable=False)

    op.alter_column(
        "stocks",
        "shares_number",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "stocks",
        "target_repartition",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("stocks", "prum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks",
        sa.Column(
            "prum",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )

    # Populate prum from cost / shares_number for existing rows
    op.execute(
        "UPDATE stocks SET prum = cost / NULLIF(shares_number, 0) WHERE prum IS NULL"
    )

    # Now make prum non-nullable
    op.alter_column("stocks", "prum", nullable=False)

    op.alter_column(
        "stocks",
        "target_repartition",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "stocks",
        "shares_number",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("stocks", "cost")
    op.drop_column("stocks", "name")
    # ### end Alembic commands ###
