"""change parts to shares

Revision ID: cf066abd5a88
Revises: 15c442166fc9
Create Date: 2025-12-22 20:35:35.463247

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf066abd5a88"
down_revision: Union[str, Sequence[str], None] = "15c442166fc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column as nullable first
    op.add_column("stocks", sa.Column("shares_number", sa.Integer(), nullable=True))

    # Copy data from parts_number to shares_number
    op.execute("UPDATE stocks SET shares_number = CAST(parts_number AS INTEGER)")

    # Make shares_number NOT NULL
    op.alter_column("stocks", "shares_number", nullable=False)

    # Drop the old column
    op.drop_column("stocks", "parts_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the old column as nullable first
    op.add_column(
        "stocks",
        sa.Column(
            "parts_number",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )

    # Copy data from shares_number to parts_number
    op.execute(
        "UPDATE stocks SET parts_number = CAST(shares_number AS DOUBLE PRECISION)"
    )

    # Make parts_number NOT NULL
    op.alter_column("stocks", "parts_number", nullable=False)

    # Drop the new column
    op.drop_column("stocks", "shares_number")
    # ### end Alembic commands ###
