[project]
name = "stock-alerting-api"
version = "0.1.0"
description = "Stock alerting API service"
authors = [
    {name = "Gireg Roussel", email = "giregroussel@free.fr"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "stock-alerting-shared",
    "yfinance>=0.2.40",
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
]

[tool.uv.sources]
stock-alerting-shared = { workspace = true }

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
